import { EXTRA_STORYBOOK_PLAN } from "./storybook-extra-books.mjs";

/**
 * 그림책(픽션) 신규 설계 척추 — 난이도 사다리 강하게 차등.
 * 텍스트 집필 워크플로우가 각 항목을 full seed JSON으로 확장한다.
 *
 * 사다리(확실한 차이):
 *   preA1: 6~7p, ~50~70 words,  1문장/p, 현재형 SVO·sight words, 반복 리듬
 *   A1   : 8~9p, ~90~120 words, 1~2문장/p, and/but, 과거형 도입, 짧은 대화
 *   A2   :10~11p,~150~190 words, 2문장/p, 과거형·because/when, 대화·문제해결
 *   B1   :12~14p,~240~320 words, 2~3문장/p, 시제 혼합·묘사·감정·주제의식
 *
 * level별 ageBand: preA1=5-7, A1=8-10, A2=8-10, B1=11-13
 * collection 필드 없음(=그림책), stage 없음 → 서재에서 level로 그룹(입문/기초/발전/심화).
 */
export const STORYBOOK_PLAN = [
  // ───────── preA1 (12) · 입문 ─────────
  { slug: "tiny-seed-grows", title: "Tiny Seed Grows", title_ko: "작은 씨앗이 자라요", level: "preA1", ageBand: "5-7", pages: 7, words: 60, char: "a tiny brown seed with a happy face, then a small green sprout, then a yellow flower", summary_ko: "작은 씨앗이 햇빛과 비를 받아 노란 꽃으로 자라는 이야기.", brief: "Seed is planted → sun warms it → rain falls → sprout pushes up → leaves grow → bud → blooms into a flower. Repetitive 'grows/up' rhythm, present tense." },
  { slug: "red-ball-rolls", title: "Red Ball Rolls", title_ko: "빨간 공이 굴러가요", level: "preA1", ageBand: "5-7", pages: 6, words: 52, char: "a bright red rubber ball with a shiny highlight", summary_ko: "빨간 공이 데굴데굴 굴러가며 동물 친구들을 만나요.", brief: "A red ball rolls down a hill, past a dog, a duck, a cat, into a basket. Repetition 'rolls', simple 'here is...'." },
  { slug: "sleepy-bear-yawns", title: "Sleepy Bear Yawns", title_ko: "졸린 곰이 하품해요", level: "preA1", ageBand: "5-7", pages: 7, words: 58, char: "a round soft brown bear cub, drowsy eyes", summary_ko: "졸린 아기 곰이 잠자리에 들기까지 하품하며 준비하는 밤.", brief: "Bear is sleepy → drinks milk → brushes → hugs toy → climbs into bed → yawns → sleeps. Cozy bedtime, present tense." },
  { slug: "duck-finds-a-puddle", title: "Duck Finds a Puddle", title_ko: "오리가 웅덩이를 찾아요", level: "preA1", ageBand: "5-7", pages: 6, words: 54, char: "a small fluffy yellow duckling", summary_ko: "아기 오리가 비 온 뒤 웅덩이를 찾아 첨벙첨벙 노는 하루.", brief: "Duckling looks for water → finds a puddle → jumps, splashes, swims, shakes → happy. Splash sounds, repetition." },
  { slug: "snail-says-hello", title: "Snail Says Hello", title_ko: "달팽이가 인사해요", level: "preA1", ageBand: "5-7", pages: 7, words: 62, char: "a small smiling snail with a swirly shell", summary_ko: "느릿느릿 달팽이가 정원 친구들에게 차례로 인사하는 이야기.", brief: "Slow snail greets a bee, a worm, a frog, a flower, the sun. 'Hello' repetition, slow/fast contrast." },
  { slug: "one-yellow-leaf", title: "One Yellow Leaf", title_ko: "노란 잎 하나", level: "preA1", ageBand: "5-7", pages: 6, words: 50, char: "a single yellow autumn leaf", summary_ko: "가을 노란 잎 하나가 바람을 타고 살랑살랑 내려앉는 이야기.", brief: "One yellow leaf on a tree → wind blows → it floats, spins, drifts → lands softly. Counting/colors, calm." },
  { slug: "kitten-and-the-yarn", title: "Kitten and the Yarn", title_ko: "아기 고양이와 실뭉치", level: "preA1", ageBand: "5-7", pages: 7, words: 64, char: "a small grey tabby kitten", summary_ko: "아기 고양이가 데굴데굴 실뭉치와 신나게 노는 이야기.", brief: "Kitten sees a yarn ball → bats it → chases → tangles → naps. Playful verbs, present tense." },
  { slug: "happy-little-cloud", title: "Happy Little Cloud", title_ko: "행복한 작은 구름", level: "preA1", ageBand: "5-7", pages: 6, words: 56, char: "a small fluffy white cloud with a gentle smile", summary_ko: "작은 구름이 하늘을 떠다니며 여러 모양으로 변하는 이야기.", brief: "A little cloud floats → becomes a sheep, a boat, a heart → waves at children. Shapes, 'I am a...' repetition." },
  { slug: "blue-fish-blows-bubbles", title: "Blue Fish Blows Bubbles", title_ko: "파란 물고기와 거품", level: "preA1", ageBand: "5-7", pages: 7, words: 60, char: "a small round blue fish with big eyes", summary_ko: "파란 물고기가 보글보글 거품을 불며 바닷속을 노는 이야기.", brief: "Blue fish blows one, two, three bubbles → bubbles rise past a crab, a starfish, up to the sun. Counting." },
  { slug: "tiny-mouse-big-cheese", title: "Tiny Mouse, Big Cheese", title_ko: "작은 쥐와 큰 치즈", level: "preA1", ageBand: "5-7", pages: 7, words: 66, char: "a tiny grey mouse with round ears", summary_ko: "작은 쥐가 자기보다 큰 치즈 한 조각을 집까지 옮기는 이야기.", brief: "Tiny mouse finds a big cheese → push, pull, roll → too heavy → a friend helps → home. Size contrast, teamwork." },
  { slug: "baby-birds-first-hop", title: "Baby Bird's First Hop", title_ko: "아기 새의 첫 폴짝", level: "preA1", ageBand: "5-7", pages: 6, words: 58, char: "a small fluffy baby bird with short wings", summary_ko: "둥지 속 아기 새가 처음으로 폴짝 뛰어 나뭇가지로 나가는 이야기.", brief: "Baby bird in nest → looks down → afraid → tries → hop! → on a branch → proud. Encouragement, repetition." },
  { slug: "moon-says-goodnight", title: "Moon Says Goodnight", title_ko: "달님이 잘 자요", level: "preA1", ageBand: "5-7", pages: 7, words: 62, char: "a soft glowing crescent moon with a calm face", summary_ko: "달님이 잠드는 동물 친구들에게 하나씩 잘 자라고 인사하는 밤.", brief: "Moon says goodnight to a rabbit, an owl, a fish, a child. Soft repetition 'Goodnight', bedtime." },

  // ───────── A1 (12) · 기초 ─────────
  { slug: "the-shy-turtle", title: "The Shy Turtle", title_ko: "부끄럼쟁이 거북이", level: "A1", ageBand: "8-10", pages: 8, words: 100, char: "a small green turtle with a patterned shell, often hiding head in shell", summary_ko: "부끄러워 등딱지에 숨던 거북이가 용기를 내어 첫 친구를 사귀는 하루.", brief: "Turtle hides from others → a frog says hi → turtle peeks → they play → turtle smiles. and/but, past simple intro." },
  { slug: "rabbits-rainy-picnic", title: "Rabbit's Rainy Picnic", title_ko: "토끼의 비 오는 소풍", level: "A1", ageBand: "8-10", pages: 9, words: 110, char: "a white rabbit with a small picnic basket", summary_ko: "소풍날 비가 오자 토끼 가족이 지혜롭게 실내 소풍으로 바꾸는 이야기.", brief: "Rabbits plan a picnic → it rains → sad → move it under a big tree / inside → still fun. Problem→solution, but/so." },
  { slug: "the-lost-mitten", title: "The Lost Mitten", title_ko: "잃어버린 벙어리장갑", level: "A1", ageBand: "8-10", pages: 8, words: 98, char: "a red wool mitten; a child in a winter coat", summary_ko: "눈밭에서 잃어버린 빨간 장갑을 동물들과 함께 찾는 이야기.", brief: "A child drops a red mitten → a squirrel, a fox find it warm → child searches → returned. Past simple, dialogue." },
  { slug: "penguin-learns-to-slide", title: "Penguin Learns to Slide", title_ko: "펭귄이 미끄럼을 배워요", level: "A1", ageBand: "8-10", pages: 9, words: 112, char: "a small black-and-white penguin chick", summary_ko: "걷기만 하던 아기 펭귄이 배로 미끄러지는 법을 배우는 이야기.", brief: "Penguin waddles, falls → a friend slides on belly → tries → wheee → loves it. Try/again, encouragement." },
  { slug: "the-littlest-firefly", title: "The Littlest Firefly", title_ko: "가장 작은 반딧불이", level: "A1", ageBand: "8-10", pages: 9, words: 108, char: "a tiny firefly with a faint glowing tail", summary_ko: "빛이 약하다고 속상하던 작은 반딧불이가 자기만의 빛을 찾는 밤.", brief: "Small firefly's light is faint → sad → helps a lost beetle find the way → glow matters. Self-worth, but/so." },
  { slug: "squirrels-acorn-hunt", title: "Squirrel's Acorn Hunt", title_ko: "다람쥐의 도토리 찾기", level: "A1", ageBand: "8-10", pages: 8, words: 102, char: "a brown squirrel with a bushy tail", summary_ko: "겨울을 앞두고 다람쥐가 도토리를 모아 숨기는 부지런한 하루.", brief: "Squirrel gathers acorns → one, two, many → hides them → forgets one → it grows into a tree. Counting, seasons." },
  { slug: "the-paper-boat", title: "The Paper Boat", title_ko: "종이배", level: "A1", ageBand: "8-10", pages: 9, words: 106, char: "a small white folded paper boat", summary_ko: "아이가 접은 종이배가 작은 개울을 따라 모험을 떠나는 이야기.", brief: "A child folds a paper boat → puts it in a stream → it floats past a duck, under a bridge → home. Journey, past." },
  { slug: "hedgehog-shares-apples", title: "Hedgehog Shares Apples", title_ko: "고슴도치가 사과를 나눠요", level: "A1", ageBand: "8-10", pages: 8, words: 100, char: "a small hedgehog with apples stuck on its spines", summary_ko: "사과를 가시에 잔뜩 꽂은 고슴도치가 친구들과 나누는 따뜻한 가을.", brief: "Hedgehog finds apples → carries on spines → too many → shares with friends → happy. Sharing, but/so." },
  { slug: "the-singing-frog", title: "The Singing Frog", title_ko: "노래하는 개구리", level: "A1", ageBand: "8-10", pages: 9, words: 110, char: "a small green frog on a lily pad", summary_ko: "밤마다 노래하는 개구리가 부끄러움을 이기고 연못 합창을 이끄는 이야기.", brief: "Frog hums alone → others ask to join → night chorus → pond sings together. Music, courage." },
  { slug: "little-cloud-and-the-rainbow", title: "Little Cloud and the Rainbow", title_ko: "작은 구름과 무지개", level: "A1", ageBand: "8-10", pages: 8, words: 104, char: "a small white cloud and a colorful rainbow arc", summary_ko: "작은 구름이 비를 내려 햇빛과 함께 무지개를 만드는 이야기.", brief: "Little cloud rains a little → sun comes → together they make a rainbow → children cheer. Cause/effect, colors." },
  { slug: "the-brave-ladybug", title: "The Brave Ladybug", title_ko: "용감한 무당벌레", level: "A1", ageBand: "8-10", pages: 9, words: 108, char: "a small red ladybug with black spots", summary_ko: "넓은 정원을 가로질러 길 잃은 동생을 찾아가는 작은 무당벌레의 용기.", brief: "Ladybug must cross the garden → past a big dewdrop, a tall stem → finds little brother → brave. Adventure." },
  { slug: "puppys-first-snow", title: "Puppy's First Snow", title_ko: "강아지의 첫 눈", level: "A1", ageBand: "8-10", pages: 8, words: 96, char: "a small brown puppy with floppy ears", summary_ko: "처음 눈을 본 강아지가 눈밭에서 신나게 뛰어노는 겨울 아침.", brief: "Puppy sees white snow → sniffs, jumps, rolls → cold nose → warm home. First experience, present/past mix." },

  // ───────── A2 (13) · 발전 ─────────
  { slug: "the-fox-and-the-bridge", title: "The Fox and the Bridge", title_ko: "여우와 다리", level: "A2", ageBand: "8-10", pages: 10, words: 170, char: "a clever orange fox; small forest animals", summary_ko: "강 건너 친구들을 만나려고 여우가 동물들과 힘을 모아 다리를 놓는 이야기.", brief: "A fox can't cross a river → asks beaver, birds, mice to help → they build a log bridge together → cross. Because/when, teamwork, dialogue." },
  { slug: "the-clockmakers-cat", title: "The Clockmaker's Cat", title_ko: "시계공의 고양이", level: "A2", ageBand: "8-10", pages: 11, words: 180, char: "a calm grey cat in an old clock shop full of clocks", summary_ko: "낡은 시계 가게의 고양이가 멈춘 큰 시계의 비밀을 찾아내는 이야기.", brief: "A cat lives among ticking clocks → the big clock stops → cat searches → finds a stuck gear (a fallen button) → fixes → ticks again. Mystery, past tense." },
  { slug: "the-mountain-echo", title: "The Mountain Echo", title_ko: "산울림", level: "A2", ageBand: "8-10", pages: 10, words: 165, char: "a curious child with a backpack on a green mountain", summary_ko: "산에서 메아리를 처음 들은 아이가 그 신비를 알아가는 하루.", brief: "A child shouts on a mountain → a voice answers → scared, then curious → learns it is an echo → plays with it. Discovery, because/so." },
  { slug: "captain-otters-river-map", title: "Captain Otter's River Map", title_ko: "수달 선장의 강 지도", level: "A2", ageBand: "8-10", pages: 11, words: 185, char: "a cheerful otter wearing a tiny captain's hat, on a little raft", summary_ko: "수달 선장이 강을 따라 내려가며 친구들과 강 지도를 완성하는 모험.", brief: "Otter rafts down a river → marks a waterfall, an island, a cave → friends add notes → finishes a map. Journey, past, sequence." },
  { slug: "the-garden-detective", title: "The Garden Detective", title_ko: "정원 탐정", level: "A2", ageBand: "8-10", pages: 10, words: 175, char: "a small mouse with a magnifying glass and notebook", summary_ko: "딸기를 누가 먹었는지, 꼬마 탐정 쥐가 단서를 따라 밝혀내는 이야기.", brief: "Strawberries are missing → mouse detective finds footprints, a feather → asks animals → it was a hungry bird → shares instead. Whodunit, because/when." },
  { slug: "the-windmill-friend", title: "The Windmill Friend", title_ko: "풍차 친구", level: "A2", ageBand: "8-10", pages: 10, words: 168, char: "an old friendly windmill with turning sails; a village child", summary_ko: "마을의 낡은 풍차가 바람이 멈춘 날 아이들의 도움으로 다시 도는 이야기.", brief: "An old windmill turns for the village → one calm day it stops → children fan it / wait for wind → it turns again → village cheers. Community, past." },
  { slug: "the-firefly-festival", title: "The Firefly Festival", title_ko: "반딧불 축제", level: "A2", ageBand: "8-10", pages: 11, words: 182, char: "many fireflies; a small rabbit watching", summary_ko: "여름밤, 반딧불이들이 모여 빛의 축제를 여는 모습을 지켜보는 토끼.", brief: "A rabbit hears about a firefly festival → waits at night → fireflies gather, blink patterns → light show → rabbit joins with a lantern. Wonder, when/because." },
  { slug: "the-bakers-tiny-helper", title: "The Baker's Tiny Helper", title_ko: "빵집의 작은 일꾼", level: "A2", ageBand: "8-10", pages: 10, words: 172, char: "a tidy little mouse; a warm bakery with bread", summary_ko: "빵집에 사는 작은 쥐가 몰래 빵집 아저씨를 도우며 우정을 쌓는 이야기.", brief: "A mouse lives in a bakery → secretly tidies spilled flour, lines up loaves → baker notices → leaves a crumb of cheese → friends. Kindness, past." },
  { slug: "the-tide-pool-treasure", title: "The Tide Pool Treasure", title_ko: "조수웅덩이 보물", level: "A2", ageBand: "8-10", pages: 11, words: 178, char: "two children with a bucket exploring rocky tide pools", summary_ko: "썰물 뒤 바위 웅덩이에서 게·소라·불가사리를 만나며 진짜 보물을 깨닫는 이야기.", brief: "Children explore tide pools → find a crab, a snail, a starfish → look for 'treasure' → realize the living things are the treasure → put them back. Nature, because/when." },
  { slug: "owls-night-school", title: "Owl's Night School", title_ko: "부엉이의 밤 학교", level: "A2", ageBand: "8-10", pages: 10, words: 170, char: "a wise owl teacher with glasses; small night animals", summary_ko: "부엉이 선생님이 밤 동물 친구들에게 별과 바람을 가르치는 즐거운 밤 수업.", brief: "An owl teaches night animals → stars, the moon, soft flying → a shy bat learns to glide → class claps. Learning, past, dialogue." },
  { slug: "the-runaway-kite", title: "The Runaway Kite", title_ko: "도망간 연", level: "A2", ageBand: "8-10", pages: 11, words: 184, char: "a bright kite with a long tail; a child chasing", summary_ko: "줄이 끊어져 날아간 연을 쫓아 마을 곳곳을 누비며 친절한 이웃을 만나는 하루.", brief: "A kite's string snaps → child chases it over a fence, a roof, a tree → neighbors help pass it back → returned. Chase, because/when, community." },
  { slug: "the-snow-lantern", title: "The Snow Lantern", title_ko: "눈 등불", level: "A2", ageBand: "8-10", pages: 10, words: 166, char: "two children building a small snow lantern with a candle", summary_ko: "추운 겨울밤, 아이들이 눈으로 등불을 만들어 골목을 따뜻하게 밝히는 이야기.", brief: "Children pack snow into a small lantern → place a candle → it glows warm → neighbors smile → winter feels cozy. Making, past, warmth." },
  { slug: "the-clever-crow", title: "The Clever Crow", title_ko: "영리한 까마귀", level: "A2", ageBand: "8-10", pages: 10, words: 174, char: "a glossy black crow beside a tall narrow jug of water", summary_ko: "물이 조금밖에 없는 깊은 병 앞에서 까마귀가 돌을 넣어 지혜롭게 물을 마시는 이야기.", brief: "A thirsty crow finds a jug with a little water it cannot reach → thinks → drops pebbles one by one → water rises → drinks. Problem-solving, because/when, classic fable tone." },

  // ───────── B1 (13) · 심화 ─────────
  { slug: "the-lighthouse-keepers-promise", title: "The Lighthouse Keeper's Promise", title_ko: "등대지기의 약속", level: "B1", ageBand: "11-13", pages: 12, words: 250, char: "an old kind lighthouse keeper; a tall striped lighthouse by the sea", summary_ko: "어떤 밤에도 불을 끄지 않겠다는 약속을 지키려 폭풍과 맞서는 등대지기의 이야기.", brief: "An old keeper promises ships he will always keep the light on → a storm breaks the lamp → he uses lanterns, his own candle → guides a lost boat home. Promise, perseverance, mixed tense, description." },
  { slug: "the-mapmakers-daughter", title: "The Mapmaker's Daughter", title_ko: "지도 만드는 사람의 딸", level: "B1", ageBand: "11-13", pages: 13, words: 270, char: "a curious girl with a satchel of papers; a cozy map workshop", summary_ko: "아버지가 못 그린 ‘안개 골짜기’를 직접 탐험해 지도를 완성하는 소녀의 모험.", brief: "A girl helps her father draw maps → one valley is always blank ('too foggy') → she hikes in, notes streams, stones, a hidden meadow → completes the map → father proud. Courage, discovery, varied tense." },
  { slug: "the-clockwork-sparrow", title: "The Clockwork Sparrow", title_ko: "태엽 참새", level: "B1", ageBand: "11-13", pages: 13, words: 280, char: "a small brass wind-up sparrow; a gentle inventor child", summary_ko: "노래를 잃은 태엽 참새가 진짜 새들과 만나 자기만의 소리를 찾는 이야기.", brief: "A child builds a wind-up sparrow that cannot sing → takes it to a garden → real birds teach it → its gears learn a tune → it sings its own song. Identity, belonging, description." },
  { slug: "the-island-of-forgotten-songs", title: "The Island of Forgotten Songs", title_ko: "잊힌 노래의 섬", level: "B1", ageBand: "11-13", pages: 13, words: 290, char: "two friends in a small boat; a misty island", summary_ko: "사람들이 잊은 옛 노래들이 모여 사는 섬을 찾아가 노래를 되살려 오는 이야기.", brief: "Two friends hear that old songs drift to a far island → they sail through mist → meet melodies that no one sings anymore → learn one → bring it home to the village. Memory, music, journey." },
  { slug: "the-greenhouse-in-winter", title: "The Greenhouse in Winter", title_ko: "겨울 온실", level: "B1", ageBand: "11-13", pages: 12, words: 255, char: "a grandmother and grandchild tending plants in a glass greenhouse", summary_ko: "눈 내리는 겨울, 할머니와 아이가 유리 온실에서 작은 봄을 키워 내는 따뜻한 이야기.", brief: "Outside it snows → inside a warm greenhouse, a child and grandmother nurse seedlings → frost cracks a pane → they patch it → first bloom opens. Patience, care, seasons, mixed tense." },
  { slug: "the-river-that-changed-its-mind", title: "The River That Changed Its Mind", title_ko: "마음을 바꾼 강", level: "B1", ageBand: "11-13", pages: 13, words: 275, char: "a winding river (gently personified); a village along its banks", summary_ko: "오래 흐르던 길을 바꾼 강 때문에 마을이 함께 새 물길을 내며 어우러지는 이야기.", brief: "A river slowly shifts its path away from a village → wells run low → people dig a new channel, plant willows → the river returns, friendlier → balance restored. Change, adaptation, description." },
  { slug: "the-boy-who-collected-echoes", title: "The Boy Who Collected Echoes", title_ko: "메아리를 모으는 아이", level: "B1", ageBand: "11-13", pages: 13, words: 285, char: "a dreamy boy with jars and a notebook in the hills", summary_ko: "골짜기마다 메아리를 병에 담아 모으던 아이가 진짜 소중한 소리를 깨닫는 이야기.", brief: "A boy 'collects' echoes in jars (a fancy of his) → labels them: laughter, thunder, a bell → loses his favorite → realizes the best sounds are the ones shared, not kept → frees them. Imagination, theme, varied tense." },
  { slug: "the-last-leaf-of-autumn", title: "The Last Leaf of Autumn", title_ko: "가을의 마지막 잎", level: "B1", ageBand: "11-13", pages: 12, words: 260, char: "one stubborn red-gold leaf on a bare tree; small animals below", summary_ko: "모두 떨어진 뒤에도 끝까지 매달린 마지막 잎이 겨울 친구들에게 희망이 되는 이야기.", brief: "All leaves fall but one clings on → animals wonder why → it shelters a cold ladybug, marks the tree for a lost bird → when spring buds come, it lets go in peace. Hope, courage, season." },
  { slug: "the-secret-of-the-tide-clock", title: "The Secret of the Tide Clock", title_ko: "조수 시계의 비밀", level: "B1", ageBand: "11-13", pages: 13, words: 280, char: "a fisher child; an old wooden clock that follows the tides", summary_ko: "바닷가 할아버지의 조수 시계가 어떻게 바다를 읽는지 알아내며 폭풍을 피하는 이야기.", brief: "A child wonders how grandfather's old 'tide clock' predicts the sea → learns it reads the moon and water → a storm nears → the clock warns them → boats come home safe. Curiosity, science-of-nature, suspense." },
  { slug: "the-night-market-of-stars", title: "The Night Market of Stars", title_ko: "별들의 밤 시장", level: "B1", ageBand: "11-13", pages: 13, words: 295, char: "a child wandering glowing stalls in the sky; friendly star-vendors", summary_ko: "꿈속에서 별들이 여는 밤 시장을 거닐며 ‘살 수 없는 것’의 가치를 배우는 이야기.", brief: "In a dream a child visits a market where stars sell wishes, songs, kindness → has no coins → a vendor says the best things are given, not bought → child gives help, receives a star. Dream, values, rich description." },
  { slug: "the-bridge-between-two-hills", title: "The Bridge Between Two Hills", title_ko: "두 언덕 사이의 다리", level: "B1", ageBand: "11-13", pages: 12, words: 265, char: "two villages of small animals on facing hills; a half-built bridge", summary_ko: "오래 떨어져 살던 두 언덕 마을이 서로를 향해 다리를 놓아 친구가 되는 이야기.", brief: "Two animal villages on facing hills never meet → a young rabbit and a young mole each start building from their side → they meet in the middle → first festival together. Cooperation, perseverance." },
  { slug: "the-girl-who-planted-light", title: "The Girl Who Planted Light", title_ko: "빛을 심은 소녀", level: "B1", ageBand: "11-13", pages: 13, words: 285, char: "a hopeful girl carrying a lantern through a dim valley", summary_ko: "빛이 부족한 골짜기에 ‘빛을 심는’ 소녀의 정성이 마을을 밝혀 가는 이야기.", brief: "A valley gets little sun → a girl plants glowing flowers (a gentle fantasy), tends them nightly → neighbors join → soft light spreads → the valley blooms warm. Hope, effort, community, description." },
  { slug: "the-storyteller-of-the-harbor", title: "The Storyteller of the Harbor", title_ko: "항구의 이야기꾼", level: "B1", ageBand: "11-13", pages: 13, words: 300, char: "an old sailor telling tales to children on a harbor dock at dusk", summary_ko: "항구의 늙은 이야기꾼이 마지막 이야기를 아이들에게 물려주며 바통을 넘기는 이야기.", brief: "An old sailor tells harbor children stories each dusk → one evening he is tired → asks a shy child to finish a tale → the child finds their voice → stories live on. Legacy, voice, warm, varied tense." },
  ...EXTRA_STORYBOOK_PLAN,
];

export default STORYBOOK_PLAN;
